matrix:
  include:
    # end-to-end integration test
    - language: python
      python: 3.7
      dist: bionic
      before_install:
        # all of this is for R and its finicky dependencies
        - sudo add-apt-repository -y "ppa:marutter/rrutter3.5"
        - sudo add-apt-repository -y "ppa:marutter/c2d4u3.5"
        - sudo add-apt-repository -y "ppa:ubuntugis/ppa"
        - sudo add-apt-repository -y "ppa:cran/travis"
        - travis_apt_get_update
        - sudo apt-get install -y --no-install-recommends
          build-essential gcc g++ libblas-dev liblapack-dev libncurses5-dev
          libreadline-dev libjpeg-dev libpcre3-dev libpng-dev zlib1g-dev
          libbz2-dev liblzma-dev libicu-dev cdbs qpdf texinfo libssh2-1-dev
          gfortran r-base-core bedtools
      install:
        - ./install_linux64.sh --skip_R
        - sudo Rscript install_R_dependencies.R
        - ./test/setup_references_test.sh
      script:
        - test/run_test.sh
        - tools/bin/bpipe errors
        - tail commandlog.txt

    # unit tests
    - language: python
      python: 3.7
      before_install:
        - sudo apt-get install bedtools
      install:
        - pip install -r requirements.txt
        - pip install pytest-cov
      script:
        - pytest -vv --cov=./
        - bash <(curl -s https://codecov.io/bash)
      after_success:
        - codecov
